// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"CargadorDesafios","status":true,"description":"","parameters":{}},
{"name":"OcultarAtacar","status":true,"description":"Oculta los comandos Atacar y Defender en batalla.","parameters":{}}
];
